Repository microsoft/BotFramework-WebChat, pull requests merged in 2019-02, with the labels that each got.

#1676 bump directlinejs to 0.11.1
  packages/bundle/package-lock.json
  packages/bundle/package.json
  packages/bundle/src/createDirectLine.js
  packages/component/package-lock.json
  packages/component/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/playground/package-lock.json
  packages/playground/package.json
Labels: 4.3

#1670 Extend style options to support basic adaptive cards style
  CHANGELOG.md
  __tests__/__image_snapshots__/chrome-docker/basic-js-setup-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-with-avatar-initials-2-attachments-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-with-avatar-initials-4-attachments-and-message-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-with-avatar-initials-4-attachments-and-no-message-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-with-avatar-initials-4-attachments-and-no-message-2-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-2-attachments-with-wide-screen-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-4-attachments-and-message-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-4-attachments-and-message-2-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-4-attachments-and-no-message-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-4-attachments-and-no-message-2-snap.png
  __tests__/__image_snapshots__/chrome-docker/stacked-js-stacked-with-avatar-initials-1-attachment-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/stacked-js-stacked-with-avatar-initials-1-attachment-with-wide-screen-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/stacked-js-stacked-without-avatar-initials-1-attachment-with-wide-screen-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/suggested-actions-js-suggested-actions-command-should-show-response-from-bot-and-no-text-from-user-on-imback-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/suggested-actions-js-suggested-actions-command-should-show-response-from-bot-and-no-text-from-user-on-messageback-1-snap.png
  packages/component/src/Styles/Fonts.js
  packages/component/src/Styles/StyleSet/Avatar.js
  packages/component/src/Styles/StyleSet/DictationInterims.js
  packages/component/src/Styles/StyleSet/DownloadAttachment.js
  packages/component/src/Styles/StyleSet/ErrorBox.js
  packages/component/src/Styles/StyleSet/SendBoxTextBox.js
  packages/component/src/Styles/StyleSet/SendStatus.js
  packages/component/src/Styles/StyleSet/SuggestedAction.js
  packages/component/src/Styles/StyleSet/TextContent.js
  packages/component/src/Styles/StyleSet/Timestamp.js
  packages/component/src/Styles/adaptiveCardHostConfig.js
  packages/component/src/Styles/defaultStyleSetOptions.js
Labels: 4.3

#1700 Bump botframework-directlinejs@0.11.2 in Ibiza
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ibiza

#1698 Add `autoFocus` props to Web Chat
  CHANGELOG.md
  README.md
  package-lock.json
  src/Chat.tsx
  src/Shell.tsx
Labels: v3

#1706 Hide suggested actions not destinated to the user
  CHANGELOG.md
  __tests__/__image_snapshots__/chrome-docker/suggested-actions-js-suggested-actions-command-should-not-show-suggested-actions-not-destinated-for-the-user-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/suggested-actions-js-suggested-actions-command-should-not-show-suggested-actions-not-destined-for-the-user-1-snap.png
  __tests__/suggestedActions.js
  packages/core/src/sagas/incomingActivitySaga.js
Labels: 4.3

#1704 Ponyfilling window.open
  CHANGELOG.md
  README.md
  __tests__/__image_snapshots__/chrome-docker/card-action-middleware-js-card-action-open-url-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/card-action-middleware-js-card-action-signin-1-snap.png
  __tests__/cardActionMiddleware.js
  __tests__/setup/setupTestFramework.js
  __tests__/setup/web/index.html
  packages/component/src/Composer.js
  packages/component/src/Middleware/CardAction/createCoreMiddleware.js
  packages/component/src/Utils/observableToPromise.js
  samples/18.customization-open-url/README.md
  samples/18.customization-open-url/index.html
Labels: 4.3

#1725 Bump react-scroll-to-bottom@1.3.1
  packages/component/package-lock.json
  packages/component/package.json
Labels: 4.3

#1685 Revert `conversationUpdate` and update tests
  CHANGELOG.md
  __tests__/__image_snapshots__/chrome-docker/basic-js-setup-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/card-action-middleware-js-card-action-open-url-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/card-action-middleware-js-card-action-signin-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-with-avatar-initials-1-attachment-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-with-avatar-initials-1-attachment-with-wide-screen-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-with-avatar-initials-2-attachments-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-with-avatar-initials-2-attachments-with-wide-screen-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-with-avatar-initials-4-attachments-and-message-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-with-avatar-initials-4-attachments-and-message-2-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-with-avatar-initials-4-attachments-and-no-message-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-with-avatar-initials-4-attachments-and-no-message-2-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-1-attachment-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-1-attachment-with-wide-screen-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-2-attachments-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-2-attachments-with-wide-screen-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-4-attachments-and-message-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-4-attachments-and-message-2-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-4-attachments-and-no-message-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/carousel-js-carousel-without-avatar-initials-4-attachments-and-no-message-2-snap.png
  __tests__/__image_snapshots__/chrome-docker/offline-ui-js-offline-ui-should-display-send-failed-retry-when-activity-is-not-able-to-send-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/offline-ui-js-offline-ui-should-display-send-failed-retry-when-activity-is-sent-but-not-acknowledged-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/stacked-js-stacked-with-avatar-initials-1-attachment-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/stacked-js-stacked-with-avatar-initials-1-attachment-with-wide-screen-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/stacked-js-stacked-with-avatar-initials-4-attachments-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/stacked-js-stacked-without-avatar-initials-1-attachment-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/stacked-js-stacked-without-avatar-initials-1-attachment-with-wide-screen-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/stacked-js-stacked-without-avatar-initials-4-attachments-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/suggested-actions-js-suggested-actions-command-should-not-show-suggested-actions-not-destinated-for-the-user-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/suggested-actions-js-suggested-actions-command-should-not-show-suggested-actions-not-destined-for-the-user-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/suggested-actions-js-suggested-actions-command-should-show-correctly-formatted-buttons-when-suggested-actions-are-displayed-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/suggested-actions-js-suggested-actions-command-should-show-response-from-bot-and-no-text-from-user-on-imback-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/suggested-actions-js-suggested-actions-command-should-show-response-from-bot-and-no-text-from-user-on-messageback-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/suggested-actions-js-suggested-actions-command-should-show-response-from-bot-and-no-text-from-user-on-postback-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/suggested-actions-js-suggested-actions-command-should-show-response-from-bot-and-text-from-user-on-messageback-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/suggested-actions-js-suggested-actions-command-should-show-response-from-bot-and-text-from-user-on-postback-1-snap.png
  __tests__/__image_snapshots__/chrome-docker/username-js-send-username-in-activity-1-snap.png
  __tests__/basic.js
  __tests__/cardActionMiddleware.js
  __tests__/carousel.js
  __tests__/constants.json
  __tests__/offlineUI.js
  __tests__/sendTypingIndicator.js
  __tests__/setup/conditions/botConnected.js
  __tests__/setup/setupTestFramework.js
  __tests__/setup/web/index.html
  __tests__/stacked.js
  __tests__/suggestedActions.js
  __tests__/username.js
  packages/core/src/sagas.js
  packages/core/src/sagas/sendConversationUpdateOnConnectSaga.js
Labels: 4.3
