Repository microsoft/BotFramework-WebChat, pull requests merged in 2019-12, with the labels that each got.

#2654 Update corejs modules
  CHANGELOG.md
  packages/bundle/src/index-es5.ts
Labels: Pre-release: Need Manual Testing

#2659 #2658 Fix rendering of markdown images in IE11
  CHANGELOG.md
  packages/component/src/Styles/StyleSet/TextContent.js
Labels: Pre-release: Need Manual Testing, R7

#2710 Reduce wasted render for activities
  CHANGELOG.md
  packages/component/src/BasicTranscript.js
  packages/component/src/hooks/internal/useMemoArrayMap.js
Labels: Pre-release: Need Manual Testing, R7

#2712 Fix Suggested Actions accessibility
  CHANGELOG.md
  packages/component/src/SendBox/SuggestedActions.js
Labels: Pre-release: Need Manual Testing, R7

#2719 Add Object.is polyfill
  CHANGELOG.md
  packages/bundle/src/index-es5.ts
Labels: Pre-release: Need Manual Testing

#2738 [P0] Bump to 4.7.2-0
  package-lock.json
  package.json
Labels: P0, R8

#2715 Linting fixes
  samples/01.d.getting-started-es5-direct-line-speech/README.md
  samples/06.i.direct-line-speech/index.html
  samples/13.b.customization-smart-display/README.md
Labels: R8

#2739 Add 4.7.0 and 4.7.1 to embed servicing plan
  packages/embed/servicingPlan.json
Labels: R8

#2652 Add React Hooks for customization (part 14)
  CHANGELOG.md
  samples/03.a.host-with-react/index.html
  samples/08.customization-user-highlighting/README.md
  samples/08.customization-user-highlighting/index.html
  samples/09.customization-reaction-buttons/README.md
  samples/09.customization-reaction-buttons/index.html
  samples/10.b.customization-password-input/README.md
  samples/10.b.customization-password-input/index.html
  samples/22.change-locale/index.html
Labels: QOL, R8

#2777 Improve test reliability
  CHANGELOG.md
  __tests__/adaptiveCards.js
  __tests__/basic.js
  __tests__/bubbleBorder.js
  __tests__/bubbleNub.js
  __tests__/cardActionMiddleware.js
  __tests__/carousel.js
  __tests__/clockSkew.js
  __tests__/constants.json
  __tests__/focus.js
  __tests__/hooks/useLanguage.js
  __tests__/hooks/useSendBoxSpeechInterimsVisible.js
  __tests__/hooks/useTextBox.js
  __tests__/inputHint.consecutive.js
  __tests__/markdown.js
  __tests__/richCards.js
  __tests__/sendTypingIndicator.js
  __tests__/setup/conditions/negate.js
  __tests__/setup/conditions/negationOf.js
  __tests__/setup/conditions/scrollToBottomCompleted.js
  __tests__/setup/web/index.html
  __tests__/speech.recognition.js
  __tests__/speech.synthesis.js
  __tests__/stacked.js
  __tests__/styleOptions.js
  __tests__/suggestedActions.js
  __tests__/timestamp.js
  __tests__/upload.js
  __tests__/video.js
Labels: QOL, R8

#2778 Fix samples/index.html for IE11
  samples/index.html
Labels: QOL
